version: '3.7'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./site-content:/var/www/html
      - ./logs:/var/log/nginx
    depends_on:
      - php
      - geoipupdate

  php:
    image: php:8.2-fpm
    volumes:
      - ./site-content:/var/www/html
      - ./GeoIP:/usr/share/GeoIP

  geoipupdate:
    image: maxmindinc/geoipupdate
    env_file:
      - .env
    volumes:
      - ./GeoIP:/usr/share/GeoIP